id: I5A4A90D2
legacy_id: P010447
ocr_import_info:
  bdrc_scan_id: W1KG15471
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T13:35:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:20:30.974238+00:00'
last_modified: 2022-08-31 16:21:34.920408
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15471
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15471
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བསྟན་པའི་དབང་ཕྱུག ༼གློག་ཀླད་པར་མ།༽
  author: ཁང་སར་བསྟན་པའི་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.8840838719007595
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG16261:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16261
      total_pages: 514
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG16261.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9232311995394695
    legacy_id: v003
  I1KG16266:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16266
      total_pages: 258
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG16266.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8429953279931045
    legacy_id: v008
  I1KG16263:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16263
      total_pages: 234
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG16263.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8712551790567009
    legacy_id: v005
  I1KG16265:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16265
      total_pages: 296
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG16265.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8847436057699697
    legacy_id: v007
  I1KG16260:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16260
      total_pages: 2
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG16260.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9663402143212938
    legacy_id: v002
  I1KG16262:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16262
      total_pages: 316
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG16262.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8555850430034307
    legacy_id: v004
  I1KG16259:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16259
      total_pages: 346
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16259.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8847849277422005
    legacy_id: v001
  I1KG16264:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16264
      total_pages: 238
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG16264.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.886037920918338
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
