id: I5A4A90D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:37:18+00:00'
last_modified: '2022-06-08T13:40:32.826989+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15471
  title: གསུང་འབུམ། བསྟན་པའི་དབང་ཕྱུག ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D262:
      image_group_id: I1KG16259
      title: ''
      total_pages: 346
      order: 1
      base_file: D262.txt
    '9086':
      image_group_id: I1KG16260
      title: ''
      total_pages: 2
      order: 2
      base_file: 9086.txt
    C005:
      image_group_id: I1KG16261
      title: ''
      total_pages: 514
      order: 3
      base_file: C005.txt
    22E2:
      image_group_id: I1KG16262
      title: ''
      total_pages: 316
      order: 4
      base_file: 22E2.txt
    63EC:
      image_group_id: I1KG16263
      title: ''
      total_pages: 234
      order: 5
      base_file: 63EC.txt
    98CA:
      image_group_id: I1KG16264
      title: ''
      total_pages: 238
      order: 6
      base_file: 98CA.txt
    7F34:
      image_group_id: I1KG16265
      title: ''
      total_pages: 296
      order: 7
      base_file: 7F34.txt
    E28A:
      image_group_id: I1KG16266
      title: ''
      total_pages: 258
      order: 8
      base_file: E28A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
